modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "stockmarket"
version = "${version}"
displayName = "Stock Market"
authors = "Alex Krieg"
description = '''
Stock Market Mod that allows players to buy and sell goods on a virtual market.
'''
#logoFile = ""

[[dependencies.stockmarket]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stockmarket]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stockmarket]]
modId = "architectury"
mandatory = true
versionRange = "[7.1.86,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.stockmarket]]
modId = "banksystem"
mandatory = true
versionRange = "[1.4.0, 1.5.0)"
ordering = "BEFORE"
side = "BOTH"