modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "stockmarket"
version = "${version}"
displayName = "Stock Market"
authors = "Alex Krieg"
description = '''
Stock Market Mod that allows players to buy and sell goods on a virtual market.
'''
#logoFile = ""

[[dependencies.stockmarket]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stockmarket]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stockmarket]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.stockmarket]]
modId = "banksystem"
mandatory = true
versionRange = "[1.4.0, 1.5.0)"
ordering = "BEFORE"
side = "BOTH"

